baseURL = "https://sexyfeifan.github.io/"
languageCode = "zh-cn"
title = "sexyfeifan Blog"
theme = "github-style"

[params]
  author = "sexyfeifan"
  description = "A Hugo blog powered by github-style theme."
  rss = true
  lastmod = true
  enableSearch = true

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
